version: '3.1'
services:
  tests:
    image: cimg/node:20.9
    entrypoint: /bin/bash
    tty: true
    environment:
      - LOCALSTACK_HOST=localstack
    env_file:
      - .docker/local.env    
    volumes:
      - ./:/app

  localstack:
    image: localstack/localstack:1.3.1
    env_file:
      - .docker/local.env
    ports:
      - '4566:4566'
    volumes:
      - ./.docker/localstack:/docker-entrypoint-initaws.d
    environment:
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - DEBUG=1
      - SERVICES=dynamodb
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - EXTRA_CORS_ALLOWED_HEADERS=Content-Disposition, Content-Type, x-amz-acl
      - EXTRA_CORS_EXPOSE_HEADERS=ETag
      - HOSTNAME_EXTERNAL=localstack

  mysql:
    image: mysql:8.0
    env_file:
      - ./.docker/local.env
    ports:
      - '3310:3306'
    volumes:
      - .docker/mysql/schema:/docker-entrypoint-initdb.d:delegated
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - TZ=US/Central
    command:
      - mysqld
      - --sql_mode=NO_ENGINE_SUBSTITUTION
      - --character-set-server=UTF8MB3 
      - --collation-server=utf8_unicode_ci 
      - --default_authentication_plugin=mysql_native_password
